%YAML:1.0

# camera intrinsics
# camera
camera.cx: 318.1
camera.cy: 258.9
camera.fx: 520.0
camera.fy: 520.0

camera.depth_scale: 1000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
